// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxYs73VQpybt0DwBUxPl8pmhomzvvPTJo',
    appId: '1:572279728838:web:05ad310c5511e14f0185c7',
    messagingSenderId: '572279728838',
    projectId: 'firestoreplayground-a017b',
    authDomain: 'firestoreplayground-a017b.firebaseapp.com',
    storageBucket: 'firestoreplayground-a017b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe2i10cfgIdCI-L8BTUtyWj1B8P3CJo7k',
    appId: '1:572279728838:android:983f3662a71350390185c7',
    messagingSenderId: '572279728838',
    projectId: 'firestoreplayground-a017b',
    storageBucket: 'firestoreplayground-a017b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD85krtEmcaHfyp5v0_EsXQf1NzdS8ZdEs',
    appId: '1:572279728838:ios:c5c75e5db8d01c840185c7',
    messagingSenderId: '572279728838',
    projectId: 'firestoreplayground-a017b',
    storageBucket: 'firestoreplayground-a017b.appspot.com',
    androidClientId: '572279728838-ate9jljd61hku42qscqu0u35nhdce5j3.apps.googleusercontent.com',
    iosClientId: '572279728838-2kchbp960scn16fr8gk70ojl1ua1814q.apps.googleusercontent.com',
    iosBundleId: 'com.doops.workspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD85krtEmcaHfyp5v0_EsXQf1NzdS8ZdEs',
    appId: '1:572279728838:ios:0de6d3b0b105ab220185c7',
    messagingSenderId: '572279728838',
    projectId: 'firestoreplayground-a017b',
    storageBucket: 'firestoreplayground-a017b.appspot.com',
    androidClientId: '572279728838-ate9jljd61hku42qscqu0u35nhdce5j3.apps.googleusercontent.com',
    iosClientId: '572279728838-umgdl55scgbsp2bv430uje26h08gc9l5.apps.googleusercontent.com',
    iosBundleId: 'com.doops.workspace.RunnerTests',
  );
}
